version: '3.8'
services:
  web:
    image: ghcr.io/imitari/imitari:latest
    container_name: imitari
    restart: always
    volumes:
      - ./public:/usr/local/bin/public
      - ./templates:/usr/local/bin/templates
      - ./static:/usr/local/bin/static
    environment:
      BASE_URL: ""
      AUTH_TOKEN: ""
      AUTH_USER: ""
      AUTH_PASSWORD: ""
      NAME: ""
      URL: "0.0.0.0"
      PORT: "9000" # Run on any port you wish

