on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Docker Image CI

jobs:
  push_to_registry:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Log in to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: andrevuillemot160
          password: ${{ secrets.GB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/imitari/imitari:latest
